name: snaphunt
description: SnapHunt - Flutter Philippines Hackathon 2019 Entry

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # firebase
  firebase_core: ^0.4.4+3

  # realtime db
  cloud_firestore: ^0.13.5

  # ml
  firebase_ml_vision: ^0.9.3+8

  # auth
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4

  # di
  provider: ^3.1.0+1

  # qr
  qr_flutter: ^3.2.0
  flutter_barcode_scanner: ^1.0.0

  # camera feed
  camera: ^0.5.7+4
  path_provider: ^1.6.7

  # vibrator
  vibration: ^1.2.4

  # check connectivity
  connectivity: ^0.4.8+5

  # autosize text
  auto_size_text: ^2.1.0

  # local db
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2

  # screenshot widget
  screenshot: ^0.1.1

  # share images
  esys_flutter_share: ^1.0.2

  expandable: ^3.0.1

   # wave
  wave: ^0.0.8

  # list animations are <3
  flutter_staggered_animations: ^0.1.2

  # introduction
  intro_views_flutter: '^2.8.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter_native_splash:
  image: assets/splash.png
  color: "ffffff"
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/default.json
    - assets/top.png
    - assets/main.png
    - assets/trophy.png
    - assets/intro_one.png
    - assets/intro_two.png
    - assets/intro_three.png
    - assets/intro_four.png
    - assets/intro_five.png
    - assets/intro_six.png
  
  fonts:
  - family: SF_Atarian_System
    fonts:
    - asset: assets/fonts/SF_Atarian_System.ttf
    - asset: assets/fonts/SF_Atarian_System_Bold.ttf
      weight: 700